branch-defaults:
  master:
    environment: production
global:
  application_name: mont-experiences-api
  branch: null
  default_ec2_keyname: null
  default_platform: Ruby 2.3 (Passenger Standalone)
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
